version: '1'
services:
  mysql:
    image: mysql:5.7.25
    container_name: todo-mysql
    restart: always
    ports:
    - 3309:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
    - ./mysql-data/db:/var/lib/mysql
  todoapp:
    #image: mohamedalichakroun/todoapp:0.0.1
    build: .
    container_name: todo-back
    depends_on:
    - mysql
    environment:
    - spring.datasource.url = jdbc:mysql://todo-mysql:3306/todoDB?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=Africa/Tunis&useLegacyDatetimeCode=false
    ports:
    - 8080:8080